# Generated by Django 2.0.1 on 2018-01-26 19:53

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import jsonfield.fields
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productList', jsonfield.fields.JSONField()),
                ('isAssigned', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('CT', 'Completing'), ('RD', 'Ready'), ('CD', 'Collected')], default='CT', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(blank=True, max_length=40)),
                ('priviledge', enumfields.fields.EnumField(enum=orders.models.PRIVILEDGE, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('image', models.ImageField(default='', upload_to='media')),
                ('price', models.IntegerField(default='10')),
            ],
        ),
        migrations.CreateModel(
            name='Product_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Product', max_length=70)),
                ('image', models.ImageField(default='', upload_to='media')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Product_category'),
        ),
    ]
