# Generated by Django 2.0rc1 on 2017-12-27 19:36

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAssigned', models.BooleanField(default=False)),
                ('status', enumfields.fields.EnumField(default=('DuringCompletion',), enum=orders.models.STATUS, max_length=10)),
                ('paymentMethod', enumfields.fields.EnumField(default='Cash', enum=orders.models.STATUS, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=40)),
                ('priviledge', enumfields.fields.EnumField(enum=orders.models.PRIVILEDGE, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='assignee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='orders.Person'),
        ),
        migrations.AddField(
            model_name='order',
            name='productList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Product'),
        ),
    ]
