# Generated by Django 2.0.1 on 2018-01-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_category',
            name='representingImage',
            field=models.CharField(default='someurl', max_length=1000),
        ),
    ]
