# Generated by Django 2.0.1 on 2018-01-20 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180120_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='imageURL',
        ),
        migrations.RenameField(
            model_name='product_category',
            old_name='representingImage',
            new_name='imageURL',
        ),
    ]
