# Generated by Django 2.0.1 on 2018-01-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180120_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imageURL',
        ),
        migrations.RemoveField(
            model_name='product_category',
            name='imageURL',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='media'),
        ),
        migrations.AddField(
            model_name='product_category',
            name='image',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
