# Generated by Django 2.0.1 on 2018-01-24 23:16

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180123_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default='10'),
        ),
        migrations.AlterField(
            model_name='order',
            name='productList',
            field=jsonfield.fields.JSONField(default=''),
        ),
    ]
