# Generated by Django 2.0.1 on 2018-01-25 18:06

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20180125_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='productList',
            field=jsonfield.fields.JSONField(default=''),
        ),
    ]
