# Generated by Django 2.0.1 on 2018-01-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='isAssigned',
            field=models.BooleanField(default=True),
        ),
    ]
